name: Deploy to Pages (crazy-max/ghaction-github-pages)

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          API_URL: 'https://blog-cms-backend-2000.herokuapp.com/api'
          MEDIA_URL: 'https://blog-cms-backend-2000.herokuapp.com/media'
          LOCALES: 'hu,en'
          DEFAULT_LOCALE: 'hu'
          PUBLIC_URL: 'https://devgellert.github.io/webpack-blog'
          HTML_EXTENSION_IN_URL: 'false'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gp-pages
          build_dir: dist
          jekyll: false
          keep_history: false
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
